FROM node:18-alpine

WORKDIR /app

COPY package.json .

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 3001
# TODO: sesuaikan port tiap service
# user-service   → 3001
# movie-service  → 3002
# review-service → 3003

CMD ["node", "server.js"]